// Base toast classes
export const toastBaseClasses = [
  'max-w-[400px]',
  'min-w-[320px]',
  'min-h-[56px]',
  'flex',
  'items-center',
  'justify-between',
  'p-4',
  'rounded-[8px]',
  'shadow-lg',
  'bg-white',
  'text-app-foreground',
  'transition-all duration-300 ease-in-out',
  'data-[state=closed]:animate-hide',
  'data-[state=open]:animate-slideIn',
  'data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)]',
  'data-[swipe=move]:transition-none',
  'data-[swipe=cancel]:translate-x-0',
  'data-[swipe=cancel]:transition-transform',
  'data-[swipe=cancel]:duration-300',
  'data-[swipe=cancel]:ease-out',
  'data-[swipe=end]:animate-slideRight',
  'touch-none',
].join(' ')
